### ISSUE TITLE
Maaaan

### ISSUE THREAD

**Issue by zimice** [teodorjuravlea/Multithreaded-Client-Sever-File-Transfer-over-TCP-in-Java#1]
Imagine you create a repository with a typo.
Quite a bummer

**Comment by teodorjuravlea** [comment]
:skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull:

**Comment by teodorjuravlea** [comment]
@zimice thanks for pointing it out xddd

**Comment by zimice** [comment]
> 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀

It's okay, we all make mistakes. You should use ChatGPT before you do something. Just a tip for next time 🗡️ :D

**Comment by teodorjuravlea** [comment]
Fr nowadays I can't even tie my shoes without the assistance of AI.
